spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework:
      security: INFO
      web: INFO
    com.yourpackage: INFO

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://ndang2319.com,https://www.ndang2319.com}
