spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: finance-tracker-api
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_should_be_very_long_and_secure}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
